CREATE TABLE EVENT(ID int , NAME varchar(150),TIME date)
CREATE TABLE GUEST(ID int , NAME varchar(150))
CREATE TABLE EVENTS_GUESTS(EVENTS_ID int, GUESTS_ID int)

INSERT INTO EVENT(ID, NAME, TIME) VALUES (1, 'event',CURRENT_TIME);

INSERT INTO GUEST(ID, NAME) VALUES (1, 'Luc');
INSERT INTO GUEST(ID, NAME) VALUES (2, 'Jean');
INSERT INTO GUEST(ID, NAME) VALUES (3, 'Paul');
